# Generated by Django 6.0.2 on 2026-02-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
