# Generated by Django 6.0.2 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru/')),
            ],
            options={
                'verbose_name': 'Data Guru',
                'verbose_name_plural': 'Data Guru',
            },
        ),
        migrations.AlterModelOptions(
            name='profilsekolah',
            options={'verbose_name': 'Profil Sekolah', 'verbose_name_plural': 'Profil Sekolah'},
        ),
    ]
