# Generated by Django 6.0.2 on 2026-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_guru_alter_profilsekolah_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('nilai_akademik', models.FloatField()),
                ('ekstrakurikuler', models.FloatField()),
                ('kehadiran', models.FloatField()),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('risiko', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Data Siswa',
                'verbose_name_plural': 'Data Siswa',
            },
        ),
    ]
