# Generated by Django 6.0.2 on 2026-02-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('tanggal_analisis', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch Analisis',
                'verbose_name_plural': 'Batch Analisis',
            },
        ),
        migrations.CreateModel(
            name='HasilAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('kelas', models.CharField(max_length=20)),
                ('nilai_rata_rata', models.FloatField()),
                ('nilai_terendah', models.FloatField()),
                ('persentase_kehadiran', models.FloatField()),
                ('skor_ekstrakurikuler', models.IntegerField()),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('risiko', models.CharField(blank=True, max_length=50, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.analisis')),
            ],
            options={
                'verbose_name': 'Hasil Analisis Siswa',
                'verbose_name_plural': 'Hasil Analisis Siswa',
            },
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
