# Generated by Django 6.0.2 on 2026-04-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_analisis_hasilanalisis_delete_siswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='nilai_terendah',
        ),
    ]
