# Generated by Django 6.0.2 on 2026-05-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_hasilanalisis_nilai_terendah'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='jenjang',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
