# Generated by Django 6.0.2 on 2026-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_analisis_jenjang'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='dbi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
