# Generated by Django 6.0.2 on 2026-05-21 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_analisis_dbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='chi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisis',
            name='silhouette',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='pca1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='pca2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
