# Generated by Django 6.0.2 on 2026-06-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_analisis_chi_analisis_created_at_analisis_silhouette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='pca1',
        ),
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='pca2',
        ),
    ]
